backend:
  name: git-gateway
  repo: hamzafoy/mishmakery
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/c87c6081-6868-433d-af0d-033ead269601/pkce
  auth_token_endpoint: /sites/c87c6081-6868-433d-af0d-033ead269601/token
  gateway_url: https://gateway.decapbridge.com

media_library:
  name: cloudinary
  config:
    cloud_name: "dynxatbex"
    api_key: "CLOUDINARY_API_KEY"
    api_secret: "CLOUDINARY_API_SECRET"
    folder: "mishmakery"

media_folder: ""      # With cloudinary, leave blank
public_folder: ""     # With cloudinary, leave blank

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }