backend:
  name: github
  repo: hamzafoy
  branch: main
  base_url: https://mishmakery-oauth.vercel.app

media_library:
  name: cloudinary
  config:
    cloud_name: "dynxatbex"
    api_key: "CLOUDINARY_API_KEY"
    api_secret: "CLOUDINARY_API_SECRET"
    folder: "mishmakery"

media_folder: ""      # With cloudinary, leave blank
public_folder: ""     # With cloudinary, leave blank

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }